# COMMAND_BYTES
REQ_CONNECTION = "3F"
ACK_CONNECTION = "FF"
REQ_DEVICE_NAME = "02"
RET_DEVICE_NAME = "82"

# send new device name
UPD_DEVICE_NAME = "03"

# confirm update of new device name
CON_NEW_DEVICE_NAME = "83"

REQ_SENSOR_TYPE = "04"
RET_SENSOR_TYPE = "84"
REQ_STATUS = "08"
RET_STATUS = "88"
REQ_SETTING = "10"
RET_SETTING = "90"
UPD_SETTING = "20"
ACK_UPD_SETTING = "a0"
REQ_DISCONNECT = "00"
ACK_DISCONNECT = "80"

# possible sensor types
SENSOR_TYPE_TEMP = "0000"
SENSOR_TYPE_LIGHT = "0100"

# possible settings to request and update
SETTING_MIN_EXTEND = "0000"
SETTING_MAX_EXTEND = "0001"
SETTING_SENSOR_TRIG_VAL = "0002"
SETTING_OP_MODE = "0003"
SETTING_EXTEND_IN_OUT = "0004"
SETTING_EXTEND_TO_VAL = "0005"
OP_MODE_AUTO = "0000"
OP_MOPE_MANUAL = "0001"
SUCCESS = "00"
FAILURE = "11"
